### ISSUE TITLE
odaiやanswerの入力完了を共有する

### ISSUE THREAD

**Issue by toshi-pono** [21hack02win/nascalay-backend#90]
`ODAI_INPUT` (サーバー → クライアント全員)  
入力完了した人数を通知する
```json
{
  "ready": 2
}
```

**Comment by Ras96** [comment]
これは`ODAI_READY/CANCEL`が呼ばれるたびに飛ばせばよさそう？ @toshi-pono

**Comment by toshi-pono** [comment]
良さ:+1:

**Comment by Ras96** [comment]
`ODAI_INPUT`ちょっともやもやしてるけど代案が思いつかなくてかなりもやもやしてる
